// flow-typed signature: 9a8874a65c0ebb8c8d218a3d28dd1912
// flow-typed version: <<STUB>>/babel-plugin-react_v^1.0.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-react' {
  declare module.exports: any;
}
