// flow-typed signature: 037f2889cfd3e4efa5d7a420d7366951
// flow-typed version: <<STUB>>/inferno-server_v^3.7.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'inferno-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'inferno-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'inferno-server/dist/index.es' {
  declare module.exports: any;
}

declare module 'inferno-server/dist/index' {
  declare module.exports: any;
}

declare module 'inferno-server/dist/inferno-server' {
  declare module.exports: any;
}

declare module 'inferno-server/dist/inferno-server.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'inferno-server/dist/index.es.js' {
  declare module.exports: $Exports<'inferno-server/dist/index.es'>;
}
declare module 'inferno-server/dist/index.js' {
  declare module.exports: $Exports<'inferno-server/dist/index'>;
}
declare module 'inferno-server/dist/inferno-server.js' {
  declare module.exports: $Exports<'inferno-server/dist/inferno-server'>;
}
declare module 'inferno-server/dist/inferno-server.min.js' {
  declare module.exports: $Exports<'inferno-server/dist/inferno-server.min'>;
}
declare module 'inferno-server/index' {
  declare module.exports: $Exports<'inferno-server'>;
}
declare module 'inferno-server/index.js' {
  declare module.exports: $Exports<'inferno-server'>;
}
