// flow-typed signature: d4aecfab053cf5c71e97fb75ee145e06
// flow-typed version: <<STUB>>/inferno_v^3.3.1/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'inferno'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'inferno' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'inferno/dist/index.es' {
  declare module.exports: any;
}

declare module 'inferno/dist/index' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'inferno/dist/index.es.js' {
  declare module.exports: $Exports<'inferno/dist/index.es'>;
}
declare module 'inferno/dist/index.js' {
  declare module.exports: $Exports<'inferno/dist/index'>;
}
declare module 'inferno/dist/inferno.js' {
  declare module.exports: $Exports<'inferno/dist/inferno'>;
}
declare module 'inferno/dist/inferno.min.js' {
  declare module.exports: $Exports<'inferno/dist/inferno.min'>;
}
declare module 'inferno/index' {
  declare module.exports: $Exports<'inferno'>;
}
declare module 'inferno/index.js' {
  declare module.exports: $Exports<'inferno'>;
}
