// flow-typed signature: bf1a659da094c890f645f27e4079a4c6
// flow-typed version: <<STUB>>/react-server_v^0.7.3/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-server/buildutils/babel-opts' {
  declare module.exports: any;
}

declare module 'react-server/buildutils/gulp-common' {
  declare module.exports: any;
}

declare module 'react-server/target/client/__bench__/handlePage' {
  declare module.exports: any;
}

declare module 'react-server/target/client/__bench__/loggingClient' {
  declare module.exports: any;
}

declare module 'react-server/target/client/client' {
  declare module.exports: any;
}

declare module 'react-server/target/client/ClientController' {
  declare module.exports: any;
}

declare module 'react-server/target/client/ClientRequest' {
  declare module.exports: any;
}

declare module 'react-server/target/client/common' {
  declare module.exports: any;
}

declare module 'react-server/target/client/components/FragmentDataCache' {
  declare module.exports: any;
}

declare module 'react-server/target/client/components/History' {
  declare module.exports: any;
}

declare module 'react-server/target/client/components/Link' {
  declare module.exports: any;
}

declare module 'react-server/target/client/components/RootContainer' {
  declare module.exports: any;
}

declare module 'react-server/target/client/components/RootElement' {
  declare module.exports: any;
}

declare module 'react-server/target/client/components/TheFold' {
  declare module.exports: any;
}

declare module 'react-server/target/client/config' {
  declare module.exports: any;
}

declare module 'react-server/target/client/constants' {
  declare module.exports: any;
}

declare module 'react-server/target/client/context/Navigator' {
  declare module.exports: any;
}

declare module 'react-server/target/client/context/RequestContext' {
  declare module.exports: any;
}

declare module 'react-server/target/client/ExpressServerRequest' {
  declare module.exports: any;
}

declare module 'react-server/target/client/logging' {
  declare module.exports: any;
}

declare module 'react-server/target/client/logging/client' {
  declare module.exports: any;
}

declare module 'react-server/target/client/logging/common' {
  declare module.exports: any;
}

declare module 'react-server/target/client/logging/response' {
  declare module.exports: any;
}

declare module 'react-server/target/client/logging/server' {
  declare module.exports: any;
}

declare module 'react-server/target/client/logging/stats' {
  declare module.exports: any;
}

declare module 'react-server/target/client/ReactServerAgent' {
  declare module.exports: any;
}

declare module 'react-server/target/client/ReactServerAgent/Cache' {
  declare module.exports: any;
}

declare module 'react-server/target/client/ReactServerAgent/Plugins' {
  declare module.exports: any;
}

declare module 'react-server/target/client/ReactServerAgent/Request' {
  declare module.exports: any;
}

declare module 'react-server/target/client/renderMiddleware' {
  declare module.exports: any;
}

declare module 'react-server/target/client/server' {
  declare module.exports: any;
}

declare module 'react-server/target/client/util/bundleNameUtil' {
  declare module.exports: any;
}

declare module 'react-server/target/client/util/ClientCssHelper' {
  declare module.exports: any;
}

declare module 'react-server/target/client/util/DebugUtil' {
  declare module.exports: any;
}

declare module 'react-server/target/client/util/navigateTo' {
  declare module.exports: any;
}

declare module 'react-server/target/client/util/PageUtil' {
  declare module.exports: any;
}

declare module 'react-server/target/client/util/RequestLocalStorage' {
  declare module.exports: any;
}

declare module 'react-server/target/client/util/StringEscapeUtil' {
  declare module.exports: any;
}

declare module 'react-server/target/server/__bench__/handlePage' {
  declare module.exports: any;
}

declare module 'react-server/target/server/__bench__/loggingClient' {
  declare module.exports: any;
}

declare module 'react-server/target/server/client' {
  declare module.exports: any;
}

declare module 'react-server/target/server/ClientController' {
  declare module.exports: any;
}

declare module 'react-server/target/server/ClientRequest' {
  declare module.exports: any;
}

declare module 'react-server/target/server/common' {
  declare module.exports: any;
}

declare module 'react-server/target/server/components/FragmentDataCache' {
  declare module.exports: any;
}

declare module 'react-server/target/server/components/History' {
  declare module.exports: any;
}

declare module 'react-server/target/server/components/Link' {
  declare module.exports: any;
}

declare module 'react-server/target/server/components/RootContainer' {
  declare module.exports: any;
}

declare module 'react-server/target/server/components/RootElement' {
  declare module.exports: any;
}

declare module 'react-server/target/server/components/TheFold' {
  declare module.exports: any;
}

declare module 'react-server/target/server/config' {
  declare module.exports: any;
}

declare module 'react-server/target/server/constants' {
  declare module.exports: any;
}

declare module 'react-server/target/server/context/Navigator' {
  declare module.exports: any;
}

declare module 'react-server/target/server/context/RequestContext' {
  declare module.exports: any;
}

declare module 'react-server/target/server/ExpressServerRequest' {
  declare module.exports: any;
}

declare module 'react-server/target/server/logging' {
  declare module.exports: any;
}

declare module 'react-server/target/server/logging/client' {
  declare module.exports: any;
}

declare module 'react-server/target/server/logging/common' {
  declare module.exports: any;
}

declare module 'react-server/target/server/logging/response' {
  declare module.exports: any;
}

declare module 'react-server/target/server/logging/server' {
  declare module.exports: any;
}

declare module 'react-server/target/server/logging/stats' {
  declare module.exports: any;
}

declare module 'react-server/target/server/ReactServerAgent' {
  declare module.exports: any;
}

declare module 'react-server/target/server/ReactServerAgent/Cache' {
  declare module.exports: any;
}

declare module 'react-server/target/server/ReactServerAgent/Plugins' {
  declare module.exports: any;
}

declare module 'react-server/target/server/ReactServerAgent/Request' {
  declare module.exports: any;
}

declare module 'react-server/target/server/renderMiddleware' {
  declare module.exports: any;
}

declare module 'react-server/target/server/server' {
  declare module.exports: any;
}

declare module 'react-server/target/server/util/bundleNameUtil' {
  declare module.exports: any;
}

declare module 'react-server/target/server/util/ClientCssHelper' {
  declare module.exports: any;
}

declare module 'react-server/target/server/util/DebugUtil' {
  declare module.exports: any;
}

declare module 'react-server/target/server/util/navigateTo' {
  declare module.exports: any;
}

declare module 'react-server/target/server/util/PageUtil' {
  declare module.exports: any;
}

declare module 'react-server/target/server/util/RequestLocalStorage' {
  declare module.exports: any;
}

declare module 'react-server/target/server/util/StringEscapeUtil' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-server/buildutils/babel-opts.js' {
  declare module.exports: $Exports<'react-server/buildutils/babel-opts'>;
}
declare module 'react-server/buildutils/gulp-common.js' {
  declare module.exports: $Exports<'react-server/buildutils/gulp-common'>;
}
declare module 'react-server/target/client/__bench__/handlePage.js' {
  declare module.exports: $Exports<'react-server/target/client/__bench__/handlePage'>;
}
declare module 'react-server/target/client/__bench__/loggingClient.js' {
  declare module.exports: $Exports<'react-server/target/client/__bench__/loggingClient'>;
}
declare module 'react-server/target/client/client.js' {
  declare module.exports: $Exports<'react-server/target/client/client'>;
}
declare module 'react-server/target/client/ClientController.js' {
  declare module.exports: $Exports<'react-server/target/client/ClientController'>;
}
declare module 'react-server/target/client/ClientRequest.js' {
  declare module.exports: $Exports<'react-server/target/client/ClientRequest'>;
}
declare module 'react-server/target/client/common.js' {
  declare module.exports: $Exports<'react-server/target/client/common'>;
}
declare module 'react-server/target/client/components/FragmentDataCache.js' {
  declare module.exports: $Exports<'react-server/target/client/components/FragmentDataCache'>;
}
declare module 'react-server/target/client/components/History.js' {
  declare module.exports: $Exports<'react-server/target/client/components/History'>;
}
declare module 'react-server/target/client/components/Link.js' {
  declare module.exports: $Exports<'react-server/target/client/components/Link'>;
}
declare module 'react-server/target/client/components/RootContainer.js' {
  declare module.exports: $Exports<'react-server/target/client/components/RootContainer'>;
}
declare module 'react-server/target/client/components/RootElement.js' {
  declare module.exports: $Exports<'react-server/target/client/components/RootElement'>;
}
declare module 'react-server/target/client/components/TheFold.js' {
  declare module.exports: $Exports<'react-server/target/client/components/TheFold'>;
}
declare module 'react-server/target/client/config.js' {
  declare module.exports: $Exports<'react-server/target/client/config'>;
}
declare module 'react-server/target/client/constants.js' {
  declare module.exports: $Exports<'react-server/target/client/constants'>;
}
declare module 'react-server/target/client/context/Navigator.js' {
  declare module.exports: $Exports<'react-server/target/client/context/Navigator'>;
}
declare module 'react-server/target/client/context/RequestContext.js' {
  declare module.exports: $Exports<'react-server/target/client/context/RequestContext'>;
}
declare module 'react-server/target/client/ExpressServerRequest.js' {
  declare module.exports: $Exports<'react-server/target/client/ExpressServerRequest'>;
}
declare module 'react-server/target/client/logging.js' {
  declare module.exports: $Exports<'react-server/target/client/logging'>;
}
declare module 'react-server/target/client/logging/client.js' {
  declare module.exports: $Exports<'react-server/target/client/logging/client'>;
}
declare module 'react-server/target/client/logging/common.js' {
  declare module.exports: $Exports<'react-server/target/client/logging/common'>;
}
declare module 'react-server/target/client/logging/response.js' {
  declare module.exports: $Exports<'react-server/target/client/logging/response'>;
}
declare module 'react-server/target/client/logging/server.js' {
  declare module.exports: $Exports<'react-server/target/client/logging/server'>;
}
declare module 'react-server/target/client/logging/stats.js' {
  declare module.exports: $Exports<'react-server/target/client/logging/stats'>;
}
declare module 'react-server/target/client/ReactServerAgent.js' {
  declare module.exports: $Exports<'react-server/target/client/ReactServerAgent'>;
}
declare module 'react-server/target/client/ReactServerAgent/Cache.js' {
  declare module.exports: $Exports<'react-server/target/client/ReactServerAgent/Cache'>;
}
declare module 'react-server/target/client/ReactServerAgent/Plugins.js' {
  declare module.exports: $Exports<'react-server/target/client/ReactServerAgent/Plugins'>;
}
declare module 'react-server/target/client/ReactServerAgent/Request.js' {
  declare module.exports: $Exports<'react-server/target/client/ReactServerAgent/Request'>;
}
declare module 'react-server/target/client/renderMiddleware.js' {
  declare module.exports: $Exports<'react-server/target/client/renderMiddleware'>;
}
declare module 'react-server/target/client/server.js' {
  declare module.exports: $Exports<'react-server/target/client/server'>;
}
declare module 'react-server/target/client/util/bundleNameUtil.js' {
  declare module.exports: $Exports<'react-server/target/client/util/bundleNameUtil'>;
}
declare module 'react-server/target/client/util/ClientCssHelper.js' {
  declare module.exports: $Exports<'react-server/target/client/util/ClientCssHelper'>;
}
declare module 'react-server/target/client/util/DebugUtil.js' {
  declare module.exports: $Exports<'react-server/target/client/util/DebugUtil'>;
}
declare module 'react-server/target/client/util/navigateTo.js' {
  declare module.exports: $Exports<'react-server/target/client/util/navigateTo'>;
}
declare module 'react-server/target/client/util/PageUtil.js' {
  declare module.exports: $Exports<'react-server/target/client/util/PageUtil'>;
}
declare module 'react-server/target/client/util/RequestLocalStorage.js' {
  declare module.exports: $Exports<'react-server/target/client/util/RequestLocalStorage'>;
}
declare module 'react-server/target/client/util/StringEscapeUtil.js' {
  declare module.exports: $Exports<'react-server/target/client/util/StringEscapeUtil'>;
}
declare module 'react-server/target/server/__bench__/handlePage.js' {
  declare module.exports: $Exports<'react-server/target/server/__bench__/handlePage'>;
}
declare module 'react-server/target/server/__bench__/loggingClient.js' {
  declare module.exports: $Exports<'react-server/target/server/__bench__/loggingClient'>;
}
declare module 'react-server/target/server/client.js' {
  declare module.exports: $Exports<'react-server/target/server/client'>;
}
declare module 'react-server/target/server/ClientController.js' {
  declare module.exports: $Exports<'react-server/target/server/ClientController'>;
}
declare module 'react-server/target/server/ClientRequest.js' {
  declare module.exports: $Exports<'react-server/target/server/ClientRequest'>;
}
declare module 'react-server/target/server/common.js' {
  declare module.exports: $Exports<'react-server/target/server/common'>;
}
declare module 'react-server/target/server/components/FragmentDataCache.js' {
  declare module.exports: $Exports<'react-server/target/server/components/FragmentDataCache'>;
}
declare module 'react-server/target/server/components/History.js' {
  declare module.exports: $Exports<'react-server/target/server/components/History'>;
}
declare module 'react-server/target/server/components/Link.js' {
  declare module.exports: $Exports<'react-server/target/server/components/Link'>;
}
declare module 'react-server/target/server/components/RootContainer.js' {
  declare module.exports: $Exports<'react-server/target/server/components/RootContainer'>;
}
declare module 'react-server/target/server/components/RootElement.js' {
  declare module.exports: $Exports<'react-server/target/server/components/RootElement'>;
}
declare module 'react-server/target/server/components/TheFold.js' {
  declare module.exports: $Exports<'react-server/target/server/components/TheFold'>;
}
declare module 'react-server/target/server/config.js' {
  declare module.exports: $Exports<'react-server/target/server/config'>;
}
declare module 'react-server/target/server/constants.js' {
  declare module.exports: $Exports<'react-server/target/server/constants'>;
}
declare module 'react-server/target/server/context/Navigator.js' {
  declare module.exports: $Exports<'react-server/target/server/context/Navigator'>;
}
declare module 'react-server/target/server/context/RequestContext.js' {
  declare module.exports: $Exports<'react-server/target/server/context/RequestContext'>;
}
declare module 'react-server/target/server/ExpressServerRequest.js' {
  declare module.exports: $Exports<'react-server/target/server/ExpressServerRequest'>;
}
declare module 'react-server/target/server/logging.js' {
  declare module.exports: $Exports<'react-server/target/server/logging'>;
}
declare module 'react-server/target/server/logging/client.js' {
  declare module.exports: $Exports<'react-server/target/server/logging/client'>;
}
declare module 'react-server/target/server/logging/common.js' {
  declare module.exports: $Exports<'react-server/target/server/logging/common'>;
}
declare module 'react-server/target/server/logging/response.js' {
  declare module.exports: $Exports<'react-server/target/server/logging/response'>;
}
declare module 'react-server/target/server/logging/server.js' {
  declare module.exports: $Exports<'react-server/target/server/logging/server'>;
}
declare module 'react-server/target/server/logging/stats.js' {
  declare module.exports: $Exports<'react-server/target/server/logging/stats'>;
}
declare module 'react-server/target/server/ReactServerAgent.js' {
  declare module.exports: $Exports<'react-server/target/server/ReactServerAgent'>;
}
declare module 'react-server/target/server/ReactServerAgent/Cache.js' {
  declare module.exports: $Exports<'react-server/target/server/ReactServerAgent/Cache'>;
}
declare module 'react-server/target/server/ReactServerAgent/Plugins.js' {
  declare module.exports: $Exports<'react-server/target/server/ReactServerAgent/Plugins'>;
}
declare module 'react-server/target/server/ReactServerAgent/Request.js' {
  declare module.exports: $Exports<'react-server/target/server/ReactServerAgent/Request'>;
}
declare module 'react-server/target/server/renderMiddleware.js' {
  declare module.exports: $Exports<'react-server/target/server/renderMiddleware'>;
}
declare module 'react-server/target/server/server.js' {
  declare module.exports: $Exports<'react-server/target/server/server'>;
}
declare module 'react-server/target/server/util/bundleNameUtil.js' {
  declare module.exports: $Exports<'react-server/target/server/util/bundleNameUtil'>;
}
declare module 'react-server/target/server/util/ClientCssHelper.js' {
  declare module.exports: $Exports<'react-server/target/server/util/ClientCssHelper'>;
}
declare module 'react-server/target/server/util/DebugUtil.js' {
  declare module.exports: $Exports<'react-server/target/server/util/DebugUtil'>;
}
declare module 'react-server/target/server/util/navigateTo.js' {
  declare module.exports: $Exports<'react-server/target/server/util/navigateTo'>;
}
declare module 'react-server/target/server/util/PageUtil.js' {
  declare module.exports: $Exports<'react-server/target/server/util/PageUtil'>;
}
declare module 'react-server/target/server/util/RequestLocalStorage.js' {
  declare module.exports: $Exports<'react-server/target/server/util/RequestLocalStorage'>;
}
declare module 'react-server/target/server/util/StringEscapeUtil.js' {
  declare module.exports: $Exports<'react-server/target/server/util/StringEscapeUtil'>;
}
